### ISSUE TITLE
手机桌面不能显示

### ISSUE THREAD

**Issue by caipy0904** [yeetor/AndroidControl#18]
![335eae721c696b4b830a9977d98d2554](https://user-images.githubusercontent.com/9986594/53470583-0df5cd80-3a9d-11e9-92fc-85aa6aafa754.png)

手机需要装什么 minicap吗 ？

**Comment by hlmichael** [comment]
老哥，找到方法了吗

**Comment by imharryzhu** [comment]
adb看一下log，应该是ndk版本问题

**Comment by CarpCap** [comment]
我也出现了这样的问题，换了几个版本的ndk 并没有得到解决

**Comment by passself** [comment]
为啥关闭了呢？我试了高于7.0的手机都是这样，ndk-build 高版本的minicap放入shared 里面也是这样
