### ISSUE TITLE
点击位置不对，无法滑动

### ISSUE THREAD

**Issue by duanyuGit** [yeetor/AndroidControl#2]

**Comment by yeetor** [comment]
可能的原因：
1. 屏幕不是1920*1080的，这块写死了，还没时间加
2. 有些设备是需要开启触摸调试开关的，检查一下是否开启（设置 -> 开发者选项）比如小米

或者提供一下设备型号和截图~

**Comment by duanyuGit** [comment]
确实不是1920*1080的,但是我在device.js中改成我手机的实际分辨率也不行，还有其它要改的嘛？
手机三星S5，分辨率为2560*1440

**Comment by yeetor** [comment]
device.js有几处改动的地方：
323，324，338，339
还有一种就是，我开个RemoteServer，然后你插上手机开启RemoteClient，我给你调试😄。刚好试一下远程连接。
我QQ：123125808
